spring:

  datasource:
    url: 'jdbc:postgresql://localhost:5432/exhibition'
    username: 'postgres'
    password: 'password'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

